name: lint & test

on:
  push:
    branches: [ "develop" ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install tools
        run: |
          sudo apt-get update && sudo apt-get install libappindicator3-dev libgtk-3-dev librsvg2-dev libssl-dev libjavascriptcoregtk-4.0-dev libsoup2.4-dev libwebkit2gtk-4.0-dev -y

      - name: lint
        run: cargo clippy -- -D warnings

  windows:
    runs-on: windows-2022
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: lint
        run: cargo clippy -- -D warnings
