name: lint & test

on:
  push:
    branches: [ "develop" ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install tools
        run: |
          sudo apt-get update && sudo apt-get install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev -y --no-install-recommends

      - name: lint
        run: cargo clippy -- -D warnings

  windows:
    runs-on: windows-2022
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: lint
        run: cargo clippy -- -D warnings
