name: publish

on:
  push:
    tags: [ 'v*' ]

# TODO: revisit and refactor when https://github.com/tauri-apps/tauri/pull/8656 is merged
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install tools
        run: |
          sudo apt-get update && sudo apt-get install libappindicator3-dev libgtk-3-dev librsvg2-dev libssl-dev libjavascriptcoregtk-4.0-dev libsoup2.4-dev libwebkit2gtk-4.0-dev -y
          cargo install tauri-cli

      - name: patch project version
        run: |
          tag=$(echo ${{ github.ref }} | grep -Po '(?<=^refs/tags/v).*')
          version=$tag+${GITHUB_SHA:0:8}
          sed -i "0,/version/{s/0.0.0/$version/}" Cargo.toml

      - name: package appimage, deb
        run: |
          cargo tauri build --bundles appimage,deb
          cp target/release/bundle/deb/*.deb ./rism-x86_64.deb
          cp target/release/bundle/appimage/*.AppImage ./rism-x86_64.AppImage

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rism-x86_64.deb
            rism-x86_64.AppImage

  windows:
    runs-on: windows-2022
    permissions:
      contents: write
    env:
      # because grep 3.0 from 2017 refuses to do anything otherwise
      LC_ALL: en_US.utf8
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install tools
        run: |
          cargo install tauri-cli

      - name: patch project version
        shell: bash
        run: |
          tag=$(echo ${{ github.ref }} | grep -Po '(?<=^refs/tags/v).*')
          version=$tag+${GITHUB_SHA:0:8}
          sed -i "0,/version/{s/0.0.0/$version/}" Cargo.toml
          echo $version

      - name: compile binary
        run: |
          cargo tauri build --bundles msi
          cp target/release/rism.exe ./rism-x86_64.exe
          cp target/release/bundle/msi/*.msi ./rism-x86_64.msi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rism-x86_64.exe
            rism-x86_64.msi
